"use client";
import {useEffect,useState} from "react";
import {Activity,BrainCircuit,CheckCircle2,Database,ImageIcon,RefreshCw,ShieldAlert} from "lucide-react";
import {api} from "@/lib/api";
import {ErrorBox,Loading,PageHeader,RiskBadge} from "@/components/ui";

type Status=any;
function Percent({value}:{value:any}){return <>{typeof value==="number"?(value*100).toFixed(1)+"%":"—"}</>}
function ModelCard({title,icon:Icon,data}:{title:string;icon:any;data:any}){const metrics=data?.metrics||{};return <section className="card"><div className="panel-head"><div style={{display:"flex",alignItems:"center",gap:11}}><div className="feature-icon"><Icon/></div><div><h2 className="panel-title">{title}</h2><p className="panel-subtitle">{data?.model_name||"Model bundle not installed"}</p></div></div><RiskBadge risk={data?.installed||data?.available?"healthy":"warning"}/></div><div className="panel-body"><div className="metric-strip"><div><span>Runtime mode</span><b style={{fontSize:13}}>{(data?.runtime_mode||"fallback").replaceAll("_"," ")}</b></div><div><span>Dataset rows</span><b>{data?.dataset_rows||data?.aggregated_rows||data?.raw_rows||"—"}</b></div><div><span>F1 score</span><b><Percent value={metrics.f1}/></b></div><div><span>ROC AUC</span><b><Percent value={metrics.roc_auc}/></b></div></div><div style={{marginTop:18}}><p className="eyebrow">Dataset</p><p style={{fontSize:12,lineHeight:1.65,margin:"5px 0"}}>{data?.dataset||"No trained real-data model is installed in this bundle."}</p>{data?.dataset_license&&<p className="muted" style={{fontSize:10}}>License: {data.dataset_license}</p>}</div>{data?.limitations?.length>0&&<div style={{marginTop:16}}><p className="eyebrow">Deployment limits</p><ul className="muted" style={{fontSize:11,lineHeight:1.8,paddingInlineStart:20}}>{data.limitations.map((x:string)=><li key={x}>{x}</li>)}</ul></div>}</div></section>}
export default function ModelsPage(){const [data,setData]=useState<Status|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);async function load(){setBusy(true);setError("");try{setData(await api("/api/models/status"))}catch(e:any){setError(e.message)}finally{setBusy(false)}}useEffect(()=>{load()},[]);return <><PageHeader eyebrow="Model governance" title="AI model registry" subtitle="Inspect which model bundle is active, its data source, held-out metrics, runtime scope, and deployment limitations." actions={<button className="btn" onClick={load} disabled={busy}><RefreshCw size={16} className={busy?"spin":""}/> Refresh registry</button>}/>{error&&<ErrorBox message={error}/>} {!data?<Loading label="Loading AI model registry…"/>:<><div className="two-col"><ModelCard title="Generic machine risk model" icon={Activity} data={data.predictive.generic}/><ModelCard title="MetroPT air-compressor model" icon={BrainCircuit} data={data.predictive.air_compressor}/></div><div style={{marginTop:15}}><ModelCard title="Industrial visual quality model" icon={ImageIcon} data={data.quality}/></div><section className="card" style={{marginTop:15}}><div className="panel-head"><div><h2 className="panel-title">Model-use policy</h2><p className="panel-subtitle">Operational safeguards built into ForgeMind.</p></div><ShieldAlert size={19} color="var(--amber)"/></div><div className="panel-body grid-auto"><div><CheckCircle2 size={18} color="var(--green)"/><h3 style={{fontSize:13}}>Family-aware selection</h3><p className="muted" style={{fontSize:11,lineHeight:1.65}}>Specialized models are selected only for matching machine families. Other assets use the generic local model rather than receiving an impressive but meaningless prediction.</p></div><div><Database size={18} color="var(--cyan)"/><h3 style={{fontSize:13}}>Traceable provenance</h3><p className="muted" style={{fontSize:11,lineHeight:1.65}}>Every bundle exposes its dataset, license, split, threshold, metrics, version, and limitations through the API and this registry.</p></div></div></section></>}</>}
