"use client";
import {useEffect,useState} from "react";
import {Activity,Building2,Database,KeyRound,Plus,Save,Settings,ShieldCheck,Trash2,Users} from "lucide-react";
import {api} from "@/lib/api";
import {ErrorBox,Field,Loading,Modal,PageHeader,RiskBadge} from "@/components/ui";
import {useToast} from "@/components/toast-provider";

const blankFactory={name:"",location:"Ras Al Khaimah Industrial Zone",timezone:"Asia/Dubai",target_oee:85};
export default function Admin(){
  const [tab,setTab]=useState("users");const [users,setUsers]=useState<any[]>([]);const [factories,setFactories]=useState<any[]>([]);const [settings,setSettings]=useState<any[]>([]);const [logs,setLogs]=useState<any[]>([]);const [factoryOpen,setFactoryOpen]=useState(false);const [factoryForm,setFactoryForm]=useState<any>(blankFactory);const [error,setError]=useState("");const toast=useToast();
  async function load(){try{const [u,f,s,l]=await Promise.all([api<any[]>("/api/admin/users"),api<any[]>("/api/factories"),api<any[]>("/api/admin/settings"),api<any[]>("/api/admin/logs?limit=150")]);setUsers(u);setFactories(f);setSettings(s);setLogs(l);setError("")}catch(e:any){setError(e.message)}}
  useEffect(()=>{load()},[]);
  async function updateUser(id:number,changes:any){try{await api(`/api/admin/users/${id}`,{method:"PATCH",body:JSON.stringify(changes)});toast.show("User permissions updated.");load()}catch(e:any){toast.show(e.message,"error")}}
  async function resetPassword(user:any){const next=window.prompt(`Enter a new password for ${user.full_name}:`);if(!next)return;if(next.length<8){toast.show("Password must be at least 8 characters.","error");return}try{await api(`/api/admin/users/${user.id}/reset-password`,{method:"POST",body:JSON.stringify({new_password:next})});toast.show("User password reset.")}catch(e:any){toast.show(e.message,"error")}}
  async function updateSetting(row:any){try{await api(`/api/admin/settings/${row.key}`,{method:"PUT",body:JSON.stringify({value:row.value,description:row.description})});toast.show(`${row.key.replaceAll("_"," ")} saved.`);load()}catch(e:any){toast.show(e.message,"error")}}
  async function createFactory(e:React.FormEvent){e.preventDefault();try{await api("/api/factories",{method:"POST",body:JSON.stringify({...factoryForm,target_oee:Number(factoryForm.target_oee)})});toast.show("Factory created.");setFactoryOpen(false);setFactoryForm(blankFactory);load()}catch(e:any){toast.show(e.message,"error")}}
  async function editFactory(row:any){const name=window.prompt("Factory name",row.name);if(!name)return;const location=window.prompt("Location",row.location);if(location===null)return;const target=window.prompt("Target OEE",String(row.target_oee));if(target===null)return;try{await api(`/api/factories/${row.id}`,{method:"PATCH",body:JSON.stringify({name,location,target_oee:Number(target)})});toast.show("Factory updated.");load()}catch(e:any){toast.show(e.message,"error")}}
  async function removeFactory(row:any){if(!window.confirm(`Delete ${row.name}? Factories with registered machines cannot be deleted.`))return;try{await api(`/api/factories/${row.id}`,{method:"DELETE"});toast.show("Factory deleted.");load()}catch(e:any){toast.show(e.message,"error")}}
  if(error&&!users.length)return <ErrorBox message={error}/>;if(!users.length)return <Loading label="Loading administration workspace…"/>;
  const tabs=[["users","Users and roles",Users],["factories","Factories",Building2],["settings","Platform settings",Settings],["logs","Audit logs",Activity]];
  return <><PageHeader eyebrow="System governance" title="Administration" subtitle="Manage users, roles, factories, operational settings, thresholds, and traceable system activity." actions={tab==="factories"?<button className="btn btn-primary" onClick={()=>setFactoryOpen(true)}><Plus size={15}/> Add factory</button>:undefined}/><div className="tabs">{tabs.map(([key,label,Icon]:any)=><button key={key} className={`tab ${tab===key?"active":""}`} onClick={()=>setTab(key)}><Icon size={14} style={{display:"inline",marginRight:6}}/>{label}</button>)}</div>
  {tab==="users"&&<section className="card" style={{marginTop:15}}><div className="panel-head"><div><h2 className="panel-title">Local users and role access</h2><p className="panel-subtitle">New registrations start as Viewer. Grant only the privileges required for each operator.</p></div><ShieldCheck size={18} color="#67e8f9"/></div><div className="table-wrap"><table className="table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Active</th><th>Last login</th><th>Security</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><strong>{user.full_name}</strong><div className="muted" style={{fontSize:9}}>{new Date(user.created_at).toLocaleDateString()}</div></td><td>{user.email}</td><td><select className="select" style={{width:190,padding:"7px 9px"}} value={user.role} onChange={e=>updateUser(user.id,{role:e.target.value})}><option value="admin">Administrator</option><option value="factory_manager">Factory manager</option><option value="maintenance_engineer">Maintenance engineer</option><option value="quality_engineer">Quality engineer</option><option value="viewer">Viewer</option></select></td><td><button className={`btn btn-small ${user.active?"":"btn-danger"}`} onClick={()=>updateUser(user.id,{active:!user.active})}>{user.active?"Active":"Inactive"}</button></td><td>{user.last_login_at?new Date(user.last_login_at).toLocaleString():"Never"}</td><td><button className="btn btn-small" onClick={()=>resetPassword(user)}><KeyRound size={13}/> Reset</button></td></tr>)}</tbody></table></div></section>}
  {tab==="factories"&&<section className="card" style={{marginTop:15}}><div className="panel-head"><div><h2 className="panel-title">Factory registry</h2><p className="panel-subtitle">Manage plant identities, locations, time zones, OEE targets, and registered asset counts.</p></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Factory</th><th>Location</th><th>Timezone</th><th>Target OEE</th><th>Machines</th><th>Actions</th></tr></thead><tbody>{factories.map(row=><tr key={row.id}><td><strong>{row.name}</strong></td><td>{row.location}</td><td>{row.timezone}</td><td>{row.target_oee}%</td><td>{row.machine_count}</td><td><div style={{display:"flex",gap:7}}><button className="btn btn-small" onClick={()=>editFactory(row)}>Edit</button><button className="btn btn-small btn-danger" disabled={row.machine_count>0} onClick={()=>removeFactory(row)}><Trash2 size={13}/></button></div></td></tr>)}</tbody></table></div></section>}
  {tab==="settings"&&<div className="grid-auto" style={{marginTop:15}}>{settings.map((row,index)=><section className="card" style={{padding:19}} key={row.key}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><h2 style={{fontSize:15,margin:0,textTransform:"capitalize"}}>{row.key.replaceAll("_"," ")}</h2><p className="muted" style={{fontSize:10,lineHeight:1.55}}>{row.description}</p></div><Database size={18} color="#67e8f9"/></div><Field label="JSON configuration"><textarea className="textarea" style={{minHeight:170,fontFamily:"ui-monospace,monospace",fontSize:11}} value={JSON.stringify(row.value,null,2)} onChange={e=>{try{const value=JSON.parse(e.target.value);setSettings(v=>v.map((x,i)=>i===index?{...x,value}:x))}catch{}}}/></Field><button className="btn btn-primary" style={{marginTop:13,width:"100%"}} onClick={()=>updateSetting(row)}><Save size={15}/> Save setting</button></section>)}</div>}
  {tab==="logs"&&<section className="card" style={{marginTop:15}}><div className="panel-head"><div><h2 className="panel-title">Audit and integration logs</h2><p className="panel-subtitle">Authentication, users, factories, machines, maintenance, quality, reports, devices, and settings.</p></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Time</th><th>Source</th><th>Event</th><th>Result</th><th>Message</th><th>Payload</th></tr></thead><tbody>{logs.map(log=><tr key={log.id}><td>{new Date(log.created_at).toLocaleString()}</td><td>{log.source}</td><td>{log.event_type.replaceAll("_"," ")}</td><td><RiskBadge risk={log.success?"completed":"failed"}/></td><td>{log.message||"—"}</td><td><details><summary className="muted" style={{cursor:"pointer"}}>View</summary><pre className="code-block">{JSON.stringify(log.payload,null,2)}</pre></details></td></tr>)}</tbody></table></div></section>}
  <Modal open={factoryOpen} onClose={()=>setFactoryOpen(false)} title="Create factory" subtitle="Add a plant to the local operating registry."><form onSubmit={createFactory}><div style={{display:"flex",flexDirection:"column",gap:14}}><Field label="Factory name"><input className="input" value={factoryForm.name} onChange={e=>setFactoryForm({...factoryForm,name:e.target.value})} required/></Field><Field label="Location"><input className="input" value={factoryForm.location} onChange={e=>setFactoryForm({...factoryForm,location:e.target.value})}/></Field><div className="form-grid"><Field label="Timezone"><input className="input" value={factoryForm.timezone} onChange={e=>setFactoryForm({...factoryForm,timezone:e.target.value})}/></Field><Field label="Target OEE"><input className="input" type="number" min="0" max="100" step="0.1" value={factoryForm.target_oee} onChange={e=>setFactoryForm({...factoryForm,target_oee:e.target.value})}/></Field></div></div><div className="form-actions"><button type="button" className="btn" onClick={()=>setFactoryOpen(false)}>Cancel</button><button className="btn btn-primary">Create factory</button></div></form></Modal></>
}
