"use client";
import Link from "next/link";import {usePathname} from "next/navigation";import {useEffect,useMemo,useState} from "react";
import {Activity,AlertTriangle,Bell,Bot,Boxes,ChartNoAxesCombined,ChevronRight,CircleUserRound,BrainCircuit,Factory,FileBarChart,LogOut,Menu,Settings,ShieldCheck,TestTube2,Wrench,X} from "lucide-react";
import {AuthProvider,useAuth} from "@/components/auth-provider";import {ToastProvider} from "@/components/toast-provider";import {api} from "@/lib/api";import {Loading} from "@/components/ui";
const nav=[
  {href:"/dashboard",label:"Command Center",icon:Activity,roles:["all"]},
  {href:"/machines",label:"Machines",icon:Boxes,roles:["all"]},
  {href:"/predictive-maintenance",label:"Predictive Maintenance",icon:Wrench,roles:["all"]},
  {href:"/quality-control",label:"Quality Control",icon:ShieldCheck,roles:["admin","factory_manager","quality_engineer"]},
  {href:"/production",label:"Production",icon:ChartNoAxesCombined,roles:["all"]},
  {href:"/alerts",label:"Alerts",icon:AlertTriangle,roles:["all"]},
  {href:"/assistant",label:"Factory Assistant",icon:Bot,roles:["all"]},
  {href:"/simulation",label:"Digital Twin",icon:TestTube2,roles:["admin","factory_manager"]},
  {href:"/reports",label:"Reports",icon:FileBarChart,roles:["all"]},
  {href:"/models",label:"AI Models",icon:BrainCircuit,roles:["all"]},
  {href:"/admin",label:"Administration",icon:Settings,roles:["admin"]},
];
function Shell({children}:{children:React.ReactNode}){const path=usePathname();const {user,loading,logout}=useAuth();const [open,setOpen]=useState(false);const [alerts,setAlerts]=useState<any>({unread:0,critical:0});useEffect(()=>{if(!user)return;const load=()=>api<any>("/api/alerts/summary").then(setAlerts).catch(()=>{});load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[user]);const visible=useMemo(()=>nav.filter(item=>item.roles.includes("all")||!!user&&item.roles.includes(user.role)),[user]);if(loading)return <div className="screen-loader"><img src="/brand/forgemind-mark.svg" alt="ForgeMind"/><Loading label="Starting ForgeMind operations workspace…"/></div>;if(!user)return null;return <div className="app-root"><header className="topbar"><div className="topbar-inner"><div className="topbar-left"><button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><Link href="/dashboard" className="brand"><img src="/brand/forgemind-mark.svg" alt="ForgeMind AI"/><span><b>ForgeMind</b><em>AI</em></span></Link><div className="topbar-divider"/><div className="factory-switch"><Factory size={16}/><span>Smart Manufacturing Plant</span><ChevronRight size={14}/></div></div><div className="topbar-actions"><Link href="/alerts" className="notification-btn"><Bell size={19}/>{alerts.unread>0&&<span>{alerts.unread>99?"99+":alerts.unread}</span>}</Link><Link href="/profile" className="user-chip"><div className="avatar">{user.full_name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><b>{user.full_name}</b><span>{user.role.replaceAll("_"," ")}</span></div></Link><button className="icon-btn logout-btn" onClick={logout} title="Sign out"><LogOut size={18}/></button></div></div></header><aside className={`sidebar ${open?"sidebar-open":""}`}><div className="sidebar-scroll"><p className="nav-section">Operations</p><nav>{visible.map(({href,label,icon:Icon})=><Link key={href} href={href} onClick={()=>setOpen(false)} className={path.startsWith(href)?"nav-link active":"nav-link"}><Icon size={19}/><span>{label}</span>{href==="/alerts"&&alerts.critical>0&&<b className="nav-count">{alerts.critical}</b>}</Link>)}</nav><div className="side-system-card"><div className="system-card-head"><span className="pulse-dot"/><b>Local operations engine</b></div><p>Database, models, reports, and files are running on this computer.</p><Link href="/settings">System details <ChevronRight size={14}/></Link></div></div><div className="sidebar-footer"><img src="/brand/forgemind-mark.svg" alt=""/><div><b>ForgeMind AI</b><span>© Mohamad Abdullatif Ktich</span></div></div></aside>{open&&<div className="sidebar-overlay" onClick={()=>setOpen(false)}/>}<main className="app-main"><div className="page-container">{children}</div></main></div>}
export default function AppShell({children}:{children:React.ReactNode}){return <AuthProvider><ToastProvider><Shell>{children}</Shell></ToastProvider></AuthProvider>}
