"use client";
import {ReactNode,useEffect} from "react";import {X,LoaderCircle,Search,Inbox} from "lucide-react";import {usePreferences} from "@/components/preferences-provider";
export function PageHeader({eyebrow,title,subtitle,actions}:{eyebrow?:string;title:string;subtitle:string;actions?:ReactNode}){return <div className="page-header"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1 className="page-title">{title}</h1><p className="page-subtitle">{subtitle}</p></div>{actions&&<div className="page-actions">{actions}</div>}</div>}
export function Kpi({label,value,note,icon,trend}:{label:string;value:string|number;note?:string;icon?:ReactNode;trend?:string}){return <div className="kpi-card"><div className="kpi-top"><span>{label}</span>{icon&&<div className="kpi-icon">{icon}</div>}</div><div className="kpi-value">{value}</div><div className="kpi-foot">{note&&<span>{note}</span>}{trend&&<b>{trend}</b>}</div></div>}
const statusAr:Record<string,string>={healthy:"سليم",running:"قيد التشغيل",completed:"مكتمل",good:"سليم",warning:"تحذير","at_risk":"معرّضة للخطر",scheduled:"مجدول",informational:"معلوماتي",high:"مرتفع",open:"مفتوح",defective:"معيب",critical:"حرج",failed:"فشل",maintenance:"صيانة","in_progress":"قيد التنفيذ",idle:"خامل",archived:"مؤرشف",paused:"متوقف مؤقتًا"};
export function RiskBadge({risk}:{risk:string}){const {isArabic}=usePreferences();const normalized=(risk||"healthy").toLowerCase();return <span className={`risk-badge risk-${normalized.replaceAll("_","-")}`}>{isArabic?(statusAr[normalized]||normalized.replaceAll("_"," ")):normalized.replaceAll("_"," ")}</span>}
export function StatusDot({status}:{status:string}){const {isArabic}=usePreferences();const normalized=(status||"idle").toLowerCase();return <span className="status-label"><i className={`status-dot status-${normalized.replaceAll("_","-")}`}/>{isArabic?(statusAr[normalized]||normalized.replaceAll("_"," ")):normalized.replaceAll("_"," ")}</span>}
export function Empty({title="Nothing here yet",children}:{title?:string;children?:ReactNode}){return <div className="empty-state"><Inbox size={32}/><h3>{title}</h3>{children&&<p>{children}</p>}</div>}
export function Loading({label="Loading data…"}:{label?:string}){return <div className="loading-state"><LoaderCircle className="spin"/><span>{label}</span></div>}
export function ErrorBox({message}:{message:string}){return <div className="error-box">{message}</div>}
export function Modal({open,title,subtitle,onClose,children,wide=false}:{open:boolean;title:string;subtitle?:string;onClose:()=>void;children:ReactNode;wide?:boolean}){useEffect(()=>{function key(e:KeyboardEvent){if(e.key==="Escape")onClose()}if(open)document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[open,onClose]);if(!open)return null;return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className={`modal-panel ${wide?"modal-wide":""}`}><div className="modal-header"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="modal-body">{children}</div></div></div>}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function SearchInput({value,onChange,placeholder="Search…"}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="search-input"><Search size={18}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}
export function Progress({value,label}:{value:number;label?:string}){return <div><div className="progress-meta">{label&&<span>{label}</span>}<b>{Math.round(value)}%</b></div><div className="progress"><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div></div>}
