"use client";
import {useEffect,useRef,useState} from "react";
import {Bot,Database,History,MessageSquarePlus,Send,Sparkles} from "lucide-react";
import {api} from "@/lib/api";
import {Empty,ErrorBox,PageHeader} from "@/components/ui";
import {useToast} from "@/components/toast-provider";
import {usePreferences} from "@/components/preferences-provider";

const quickEn=["Which machine needs maintenance first?","Why is the highest-risk machine at risk?","Summarize current production performance.","Explain the latest quality inspection.","Give me an executive factory summary."];
const quickAr=["أي آلة تحتاج إلى الصيانة أولًا؟","لماذا الآلة الأعلى خطورة معرضة للعطل؟","لخّص أداء الإنتاج الحالي.","اشرح أحدث فحص للجودة.","أعطني ملخصًا تنفيذيًا للمصنع."];

export default function Assistant(){
  const {locale,isArabic}=usePreferences();
  const [question,setQuestion]=useState("");const [messages,setMessages]=useState<any[]>([]);const [conversations,setConversations]=useState<any[]>([]);const [conversationId,setConversationId]=useState<number|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const endRef=useRef<HTMLDivElement>(null);const toast=useToast();
  async function loadConversations(){try{setConversations(await api("/api/assistant/conversations"))}catch(e:any){setError(e.message)}}
  useEffect(()=>{loadConversations()},[]);
  useEffect(()=>{if(conversationId===null)setMessages([{role:"assistant",content:isArabic?"أحلل قاعدة بيانات ForgeMind الحالية. اسأل عن مخاطر الآلات أو أولوية الصيانة أو الإنتاج أو الجودة أو التنبيهات أو الملخص التنفيذي.":"I analyze the current ForgeMind database. Ask about machine risk, maintenance priority, production, quality, alerts, or an executive summary.",evidence:{mode:"data-grounded local engine",locale}}])},[locale,conversationId,isArabic]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"})},[messages,busy]);
  async function openConversation(id:number){try{const row:any=await api(`/api/assistant/conversations/${id}`);setConversationId(id);setMessages(row.messages);setError("")}catch(e:any){toast.show(e.message,"error")}}
  function newConversation(){setConversationId(null);setMessages([{role:"assistant",content:isArabic?"بدأ تحليل جديد للمصنع. ما الذي تريد التحقق منه؟":"New factory analysis started. What should I investigate?",evidence:{mode:"data-grounded local engine",locale}}])}
  async function send(e?:React.FormEvent,qOverride?:string){e?.preventDefault();const q=(qOverride??question).trim();if(!q||busy)return;setMessages(v=>[...v,{role:"user",content:q}]);setQuestion("");setBusy(true);try{const response:any=await api("/api/assistant/query",{method:"POST",body:JSON.stringify({question:q,conversation_id:conversationId,locale})});setConversationId(response.conversation_id);setMessages(v=>[...v,{role:"assistant",content:response.answer,evidence:response.evidence}]);loadConversations()}catch(e:any){setMessages(v=>[...v,{role:"assistant",content:isArabic?`تعذر إكمال التحليل: ${e.message}`:`I could not complete the analysis: ${e.message}`,evidence:{error:true}}])}finally{setBusy(false)}}
  const quick=isArabic?quickAr:quickEn;
  return <><PageHeader eyebrow="Data-grounded intelligence" title="AI factory assistant" subtitle="Ask operational questions. Responses are built from the machines, predictions, sensors, maintenance work, production records, quality inspections, and alerts stored in ForgeMind." actions={<button className="btn btn-primary" onClick={newConversation}><MessageSquarePlus size={16}/> New analysis</button>}/><div className="assistant-layout"><aside className="card" style={{minHeight:650}}><div className="panel-head"><div><h2 className="panel-title">Conversation history</h2><p className="panel-subtitle">Saved in the local database.</p></div><History size={17} color="var(--cyan2)"/></div><div style={{padding:10}}>{conversations.length===0?<Empty title="No saved conversations"/>:conversations.map(c=><button key={c.id} onClick={()=>openConversation(c.id)} className="conversation-row" data-active={conversationId===c.id}><b>{c.title}</b><span className="muted">{new Date(c.updated_at).toLocaleString(locale==="ar"?"ar-AE":"en-US")}</span></button>)}</div></aside><section className="card assistant-chat"><div className="panel-head"><div><h2 className="panel-title">Operations analysis</h2><p className="panel-subtitle">Grounded in current platform data, not generic factory text.</p></div><div className="data-connected"><Database size={15}/> Data connected</div></div><div className="assistant-messages">{messages.map((m,index)=><div key={m.id||index} className={`message-row ${m.role}`}><div className="message-bubble">{m.role==="assistant"&&<div className="assistant-name"><Bot size={15}/> ForgeMind Assistant</div>}<p>{m.content}</p>{m.evidence&&<details><summary className="muted">View analysis evidence</summary><pre className="code-block">{JSON.stringify(m.evidence,null,2)}</pre></details>}</div></div>)}{busy&&<div className="muted assistant-thinking"><Sparkles size={15}/> Analyzing current factory data…</div>}<div ref={endRef}/></div><div className="assistant-composer"><div className="quick-prompts">{quick.map(q=><button key={q} className="btn btn-small" onClick={()=>send(undefined,q)}>{q}</button>)}</div><form onSubmit={send}><input className="input" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask why a machine is at risk, compare assets, or summarize the factory…"/><button className="btn btn-primary" disabled={busy||!question.trim()} aria-label="Send"><Send size={16}/></button></form></div></section></div>{error&&<div style={{marginTop:15}}><ErrorBox message={error}/></div>}</>
}
