import Link from "next/link";import {Activity,ArrowRight,Bot,ChartNoAxesCombined,Factory,FileBarChart,ScanSearch,ShieldCheck,Sparkles,Wrench} from "lucide-react";
const features=[
  [Activity,"Predict machine failures","Machine-health scoring, anomaly detection, remaining useful life, root-cause signals, and maintenance priority."],
  [ScanSearch,"Inspect product quality","Surface-anomaly detection, optional golden-reference comparison, defect localization, batch history, and quality trends."],
  [ChartNoAxesCombined,"Control production performance","OEE, availability, performance, quality, downtime, shift output, rejects, and live operational signals."],
  [Bot,"Ask the factory assistant","Data-grounded answers built from machine risk, sensor readings, maintenance work, production, quality, and alerts."],
  [FileBarChart,"Generate operational reports","Executive, maintenance, quality, production, and incident reports stored locally as branded PDF records."],
  [ShieldCheck,"Operate with real workflows","Local users and roles, machine CRUD, maintenance tickets, acknowledgements, device commands, logs, and settings."],
] as const;
export default function Landing(){return <main className="hero-shell"><nav className="public-nav"><Link href="/" className="public-brand"><img src="/brand/forgemind-mark.svg" alt="ForgeMind AI"/><span>ForgeMind AI</span></Link><div className="hero-actions" style={{marginTop:0}}><Link className="btn btn-ghost" href="/docs">Documentation</Link><Link className="btn btn-primary" href="/login">Open workspace <ArrowRight size={16}/></Link></div></nav><section className="hero"><div><span className="hero-badge"><Sparkles size={14}/> Industrial intelligence, built to operate</span><h1>Turn factory signals into <span>decisions.</span></h1><p>ForgeMind AI unifies machine health, product inspection, production monitoring, maintenance workflows, alerts, reports, and industrial commands in one operational platform.</p><div className="hero-actions"><Link href="/login" className="btn btn-primary">Launch ForgeMind <ArrowRight size={17}/></Link><Link href="/docs" className="btn">Explore integration guide</Link></div><div className="hero-proof"><div><b>7</b><span>connected asset types</span></div><div><b>5</b><span>operational report types</span></div><div><b>2</b><span>visual inspection modes</span></div></div></div><div className="hero-visual"><img src="/brand/factory-hero.svg" alt="ForgeMind factory command center illustration"/></div></section><section className="feature-section"><p className="section-kicker">One industrial operations workspace</p><h2 className="section-title">From signal ingestion to maintenance action.</h2><p className="section-copy">The application is designed as a connected product rather than a collection of dashboards. Every module writes to the same local data layer and feeds the workflows around it.</p><div className="feature-grid">{features.map(([Icon,title,copy])=><article className="card card-hover feature-card" key={title}><div className="feature-icon"><Icon/></div><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="brand-band"><div><p className="section-kicker">Digital twin and hardware gateway</p><h2 className="section-title">Operate locally today. Connect the plant tomorrow.</h2><p className="section-copy">Use the included digital twin to exercise the complete sensor-to-risk-to-alert-to-maintenance flow. The hardware API and command layer are already separated so PLC, MQTT, OPC-UA, or edge gateways can replace the simulator later.</p><div className="hero-actions"><Link className="btn btn-primary" href="/login">Enter command center</Link></div></div><img src="/brand/machine-network.svg" alt="Industrial machine network illustration"/></section><footer className="public-nav" style={{borderTop:"1px solid var(--line)",color:"var(--muted)",fontSize:11}}><span>© 2026 Mohamad Abdullatif Ktich</span><span><a href="https://www.linkedin.com/in/mohamad-ktich" target="_blank" rel="noreferrer">LinkedIn</a> · <a href="https://github.com/MohamadKtich" target="_blank" rel="noreferrer">GitHub</a></span></footer></main>}
