from __future__ import annotations
from io import BytesIO, StringIO
from pathlib import Path
import csv
from datetime import datetime, timezone
from sqlalchemy import func
from sqlalchemy.orm import Session
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics.charts.linecharts import HorizontalLineChart
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import KeepTogether, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from ..config import get_settings
from ..models import Alert, Inspection, Machine, MachinePrediction, MaintenanceRecord, ProductionRecord

settings = get_settings()
REPORT_TYPES = {
    "executive": "Executive Factory Overview",
    "maintenance": "Predictive Maintenance Report",
    "quality": "Quality Control Report",
    "production": "Production Performance Report",
    "alerts": "Alert and Incident Summary",
}


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="BrandTitle", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=24, leading=29, textColor=colors.HexColor("#071827"), spaceAfter=8))
    styles.add(ParagraphStyle(name="Section", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=14, textColor=colors.HexColor("#075985"), spaceBefore=14, spaceAfter=8))
    styles.add(ParagraphStyle(name="SmallMuted", parent=styles["BodyText"], fontSize=8, textColor=colors.HexColor("#64748B")))
    styles.add(ParagraphStyle(name="Kpi", parent=styles["BodyText"], fontName="Helvetica-Bold", fontSize=17, alignment=TA_CENTER, textColor=colors.HexColor("#0F172A")))
    return styles


def _header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(colors.HexColor("#071827"))
    canvas.rect(0, A4[1] - 17 * mm, A4[0], 17 * mm, fill=1, stroke=0)
    canvas.setFillColor(colors.HexColor("#22D3EE"))
    canvas.setFont("Helvetica-Bold", 12)
    canvas.drawString(17 * mm, A4[1] - 11 * mm, "ForgeMind AI")
    canvas.setFillColor(colors.HexColor("#CBD5E1"))
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(A4[0] - 17 * mm, A4[1] - 11 * mm, "Industrial Intelligence Platform")
    canvas.setFillColor(colors.HexColor("#64748B"))
    canvas.drawString(17 * mm, 10 * mm, "Generated by ForgeMind AI local operations engine")
    canvas.drawRightString(A4[0] - 17 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _kpi_table(items: list[tuple[str, str]]) -> Table:
    cells = []
    for label, value in items:
        cells.append([Paragraph(value, _styles()["Kpi"]), Paragraph(label.upper(), ParagraphStyle(name=f"L{label}", fontName="Helvetica-Bold", fontSize=7, alignment=TA_CENTER, textColor=colors.HexColor("#64748B")))])
    table = Table([cells], colWidths=[(A4[0] - 34 * mm) / len(cells)] * len(cells))
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
        ("BOX", (0, 0), (-1, -1), .6, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), .4, colors.HexColor("#E2E8F0")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
    ]))
    return table


def _risk_chart(rows: list[tuple[str, float]]) -> Drawing:
    drawing = Drawing(500, 180)
    chart = VerticalBarChart()
    chart.x = 45
    chart.y = 30
    chart.width = 420
    chart.height = 120
    chart.data = [[value for _, value in rows]]
    chart.categoryAxis.categoryNames = [name for name, _ in rows]
    chart.categoryAxis.labels.fontSize = 7
    chart.valueAxis.valueMin = 0
    chart.valueAxis.valueMax = 100
    chart.valueAxis.valueStep = 20
    chart.bars[0].fillColor = colors.HexColor("#0891B2")
    chart.strokeColor = colors.HexColor("#CBD5E1")
    drawing.add(chart)
    return drawing


def _production_chart(rows: list[ProductionRecord]) -> Drawing:
    drawing = Drawing(500, 180)
    chart = HorizontalLineChart()
    chart.x = 45
    chart.y = 30
    chart.width = 420
    chart.height = 120
    ordered = rows[-12:]
    chart.data = [
        [float(row.produced) for row in ordered],
        [float(row.rejected) for row in ordered],
    ]
    chart.categoryAxis.categoryNames = [str(index + 1) for index in range(len(ordered))]
    chart.categoryAxis.labels.fontSize = 7
    chart.lines[0].strokeColor = colors.HexColor("#0891B2")
    chart.lines[1].strokeColor = colors.HexColor("#E11D48")
    chart.lines[0].strokeWidth = 2
    chart.lines[1].strokeWidth = 2
    drawing.add(chart)
    return drawing


def _table(data: list[list], widths: list[float] | None = None) -> Table:
    table = Table(data, repeatRows=1, colWidths=widths)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0E7490")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
        ("GRID", (0, 0), (-1, -1), .35, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return table


def build_report(db: Session, report_type: str) -> tuple[bytes, str]:
    report_type = report_type if report_type in REPORT_TYPES else "executive"
    title = REPORT_TYPES[report_type]
    styles = _styles()
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=17 * mm, leftMargin=17 * mm, topMargin=24 * mm, bottomMargin=17 * mm, title=title)
    story = [Paragraph(title, styles["BrandTitle"]), Paragraph(datetime.now(timezone.utc).strftime("Generated %d %B %Y at %H:%M UTC"), styles["SmallMuted"]), Spacer(1, 12)]

    machines = db.query(Machine).filter(Machine.archived == False).all()
    latest_predictions = []
    for machine in machines:
        prediction = db.query(MachinePrediction).filter(MachinePrediction.machine_id == machine.id).order_by(MachinePrediction.created_at.desc()).first()
        if prediction:
            latest_predictions.append((machine, prediction))
    production = db.query(ProductionRecord).order_by(ProductionRecord.recorded_at.asc()).all()
    inspections = db.query(Inspection).order_by(Inspection.created_at.desc()).limit(50).all()
    alerts = db.query(Alert).order_by(Alert.created_at.desc()).limit(50).all()
    maintenance = db.query(MaintenanceRecord).order_by(MaintenanceRecord.created_at.desc()).limit(50).all()
    produced = sum(row.produced for row in production)
    rejected = sum(row.rejected for row in production)
    downtime = sum(row.downtime_minutes for row in production)
    quality = 100 - rejected / produced * 100 if produced else 100
    critical = sum(prediction.risk_level == "critical" for _, prediction in latest_predictions)
    open_alerts = sum(not alert.acknowledged for alert in alerts)
    completed_maintenance = sum(row.status == "completed" for row in maintenance)

    story.append(_kpi_table([
        ("Produced", f"{produced:,}"),
        ("Quality", f"{quality:.1f}%"),
        ("Critical assets", str(critical)),
        ("Open alerts", str(open_alerts)),
    ]))

    if report_type in {"executive", "maintenance"}:
        story += [Paragraph("Machine health and risk", styles["Section"])]
        risk_rows = sorted([(machine.code, prediction.failure_probability * 100) for machine, prediction in latest_predictions], key=lambda item: item[1], reverse=True)
        if risk_rows:
            story.append(_risk_chart(risk_rows[:8]))
            rows = [["Machine", "Status", "Health", "Failure risk", "RUL", "Likely issue", "Priority"]]
            for machine, prediction in sorted(latest_predictions, key=lambda row: row[1].failure_probability, reverse=True):
                rows.append([machine.code, prediction.risk_level, f"{prediction.health_score:.0f}/100", f"{prediction.failure_probability:.0%}", f"{prediction.remaining_useful_hours or 0:.0f} h", prediction.likely_issue, prediction.maintenance_priority])
            story.append(_table(rows, [45, 48, 48, 56, 42, 125, 52]))
        story += [Paragraph("Maintenance work", styles["Section"])]
        task_rows = [["Machine", "Task", "Priority", "Status", "Assigned", "Schedule"]]
        for row in maintenance[:15]:
            machine = db.get(Machine, row.machine_id)
            task_rows.append([machine.code if machine else row.machine_id, row.title, row.priority, row.status, row.assigned_to or "Unassigned", row.scheduled_for or "Not scheduled"])
        story.append(_table(task_rows, [48, 150, 48, 52, 80, 80]))

    if report_type in {"executive", "production"}:
        story += [Paragraph("Production performance", styles["Section"])]
        if production:
            story.append(_production_chart(production))
        availability = 100 - (downtime / max(1, sum(row.runtime_minutes + row.downtime_minutes for row in production)) * 100)
        performance = min(100, produced / max(1, sum(row.planned for row in production)) * 100)
        oee = availability / 100 * performance / 100 * quality / 100 * 100
        story.append(_kpi_table([("Availability", f"{availability:.1f}%"), ("Performance", f"{performance:.1f}%"), ("Quality", f"{quality:.1f}%"), ("OEE", f"{oee:.1f}%")]))
        rows = [["Time", "Shift", "Line", "Planned", "Produced", "Rejected", "Downtime"]]
        for row in production[-18:][::-1]:
            rows.append([row.recorded_at.strftime("%Y-%m-%d %H:%M"), row.shift, row.line_name, row.planned, row.produced, row.rejected, f"{row.downtime_minutes:.1f}m"])
        story.append(Spacer(1, 10))
        story.append(_table(rows, [82, 34, 76, 44, 46, 44, 52]))

    if report_type in {"executive", "quality"}:
        story += [Paragraph("Quality control", styles["Section"])]
        defective = sum(row.status == "defective" for row in inspections)
        pass_rate = 100 - defective / max(1, len(inspections)) * 100
        story.append(_kpi_table([("Inspections", str(len(inspections))), ("Passed", str(len(inspections) - defective)), ("Defective", str(defective)), ("Pass rate", f"{pass_rate:.1f}%")]))
        rows = [["Time", "Product", "Batch", "Result", "Confidence", "Defects", "Mode"]]
        for row in inspections[:16]:
            rows.append([row.created_at.strftime("%Y-%m-%d %H:%M"), row.product_name, row.batch_code or "—", row.status, f"{row.confidence:.0%}", ", ".join(row.defect_types) or "None", row.inspection_mode])
        story.append(Spacer(1, 10))
        story.append(_table(rows, [74, 92, 58, 48, 52, 100, 78]))

    if report_type in {"executive", "alerts"}:
        story += [Paragraph("Alert and incident summary", styles["Section"])]
        rows = [["Time", "Severity", "Category", "Title", "Status"]]
        for row in alerts[:18]:
            rows.append([row.created_at.strftime("%Y-%m-%d %H:%M"), row.severity, row.category, row.title, "Acknowledged" if row.acknowledged else "Open"])
        story.append(_table(rows, [80, 48, 70, 200, 72]))

    story += [Spacer(1, 14), Paragraph("Operational guidance", styles["Section"]), Paragraph("ForgeMind AI combines sensor analytics, statistical anomaly detection, machine-learning risk scoring, visual inspection, and operator workflows. Validate thresholds and models against the target equipment before using automated commands in a safety-critical environment.", styles["BodyText"])]
    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buffer.getvalue(), title


def save_report(db: Session, report_type: str, user_id: int | None = None, start_date: str = "", end_date: str = ""):
    from ..models import Report
    payload, title = build_report(db, report_type)
    root = Path(settings.storage_dir) / "reports"
    root.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S-%f")
    path = root / f"forgemind-{report_type}-{stamp}.pdf"
    path.write_bytes(payload)
    row = Report(report_type=report_type, title=title, file_path=str(path), period_start=start_date, period_end=end_date, generated_by=user_id)
    db.add(row)
    db.commit()
    db.refresh(row)
    return row


def production_csv(db: Session) -> str:
    output = StringIO()
    writer = csv.writer(output)
    writer.writerow(["recorded_at", "shift", "line_name", "product_name", "planned", "produced", "rejected", "downtime_minutes", "runtime_minutes", "ideal_cycle_seconds"])
    for row in db.query(ProductionRecord).order_by(ProductionRecord.recorded_at.desc()).all():
        writer.writerow([row.recorded_at.isoformat(), row.shift, row.line_name, row.product_name, row.planned, row.produced, row.rejected, row.downtime_minutes, row.runtime_minutes, row.ideal_cycle_seconds])
    return output.getvalue()
