"use client";import {useEffect,useState} from "react";import {Download,FileBarChart,FileCheck2,FileCog,FileSpreadsheet,FileWarning,Plus} from "lucide-react";import {api,downloadAuthenticated} from "@/lib/api";import {Empty,ErrorBox,Loading,PageHeader,RiskBadge} from "@/components/ui";import {useToast} from "@/components/toast-provider";
const reportTypes=[
  {type:"executive",title:"Executive Factory Overview",copy:"KPIs, machine risk, production, quality, maintenance, and alerts.",icon:FileBarChart},
  {type:"maintenance",title:"Predictive Maintenance Report",copy:"Machine health, risk ranking, likely issues, RUL, and work orders.",icon:FileCog},
  {type:"quality",title:"Quality Control Report",copy:"Inspections, pass rate, defective batches, defect types, and traceability.",icon:FileCheck2},
  {type:"production",title:"Production Performance Report",copy:"Output, rejects, downtime, availability, performance, quality, and OEE.",icon:FileSpreadsheet},
  {type:"alerts",title:"Alert and Incident Summary",copy:"Severity, category, acknowledgement state, and incident history.",icon:FileWarning},
] as const;
export default function Reports(){const [rows,setRows]=useState<any[]>([]);const [busy,setBusy]=useState("");const [error,setError]=useState("");const toast=useToast();async function load(){try{setRows(await api("/api/reports"));setError("")}catch(e:any){setError(e.message)}}useEffect(()=>{load()},[]);async function generate(type:string){setBusy(type);try{const row:any=await api("/api/reports/generate",{method:"POST",body:JSON.stringify({report_type:type,start_date:"",end_date:""})});toast.show(`${row.title} generated.`);await load();await downloadAuthenticated(row.download_url,`forgemind-${type}.pdf`)}catch(e:any){toast.show(e.message,"error")}finally{setBusy("")}}if(error&&!rows.length)return <ErrorBox message={error}/>;return <><PageHeader eyebrow="Operational records" title="Reports and exports" subtitle="Generate branded PDF reports from current local platform data and preserve a downloadable report history." actions={<button className="btn" onClick={()=>downloadAuthenticated("/api/reports/production.csv","forgemind-production.csv")}><Download size={16}/> Export production CSV</button>}/><div className="grid-auto">{reportTypes.map(({type,title,copy,icon:Icon})=><article className="card card-hover" key={type} style={{padding:21}}><div className="feature-icon"><Icon/></div><h2 style={{fontSize:16,margin:"18px 0 7px"}}>{title}</h2><p className="muted" style={{fontSize:11,lineHeight:1.65,minHeight:54}}>{copy}</p><button className="btn btn-primary" style={{marginTop:13,width:"100%"}} onClick={()=>generate(type)} disabled={!!busy}>{busy===type?"Generating PDF…":<><Plus size={15}/> Generate and download</>}</button></article>)}</div><section className="card" style={{marginTop:15}}><div className="panel-head"><div><h2 className="panel-title">Report history</h2><p className="panel-subtitle">Generated files stored in the local report directory and database.</p></div></div>{rows.length===0?<div className="panel-body"><Empty title="No reports generated">Choose a report type above to create the first operational record.</Empty></div>:<div className="table-wrap"><table className="table"><thead><tr><th>Generated</th><th>Report</th><th>Type</th><th>Period</th><th>Download</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString()}</td><td><strong>{r.title}</strong></td><td><RiskBadge risk="informational"/></td><td>{r.period_start||"All recorded data"}</td><td><button className="btn btn-small" onClick={()=>downloadAuthenticated(r.download_url,`forgemind-${r.report_type}-${r.id}.pdf`)}><Download size={14}/> Download</button></td></tr>)}</tbody></table></div>}</section></>}
